
-- bookmarksTree =
--   [ Node (TSNode "Browser Bookmarks" "" (return ()))
--       [ Node (TSNode "Gmail" "" (browse "mail.google.com")) []
--       , Node (TSNode "Posteo" "" (browse "poste.de/en")) []
--       , Node (TSNode "LessWrong" "" (browse "lesswrong.com")) []
--       , Node (TSNode "Leetcode" "" (browse "leetcode.com")) []
--       , Node (TSNode "Cppreference" "" (browse "en.cppreference.com")) []
--       , Node (TSNode "Python docs" "" (browse "docs.python.com")) []
--       , Node (TSNode "Haskell wiki" "" (browse "wiki.haskell.org")) []
--       , Node (TSNode "Vim cheatsheet" "" (browse "vim.rotrr.com")) []
--       , Node (TSNode "Neovim docs" "" (browse "neovim.io/doc")) []
--       , Node (TSNode "Git docs" "" (browse "git-scm.com/doc")) []
--       , Node (TSNode "Arch wiki" "" (browse "wiki.archlinux.org")) []
--       , Node (TSNode "Linux manpages" "" (browse "linux.die.net/man")) []
--       , Node (TSNode "Wikichip" "" (browse "wikichip.org")) []
--       , Node (TSNode "Libgen" "" (browse "libgen.is")) []
--       , Node (TSNode "Sci-hub" "" (browse "sc-hubtw.hkvisa.net")) []
--       , Node (TSNode "Wikibooks" "" (browse "wikibooks.org")) []
--       , Node (TSNode "Open Library" "" (browse "openlibrary.org")) []
--       , Node (TSNode "arXiv" "" (browse "arxiv.org")) []
--       , Node (TSNode "SSRN" "" (browse "ssrn.com")) []
--       , Node (TSNode "Jstor" "" (browse "jstor.org")) []
--       , Node (TSNode "Lexis Nexis" "" (browse "lexisnexis.com")) []
--       , Node (TSNode "ACM Library" "" (browse "dl.acm.org")) []
--       , Node (TSNode "CIA Factbook" "" (browse "cia.gov/the-world-factbook")) []
--       , Node (TSNode "Project Euler" "" (browse "projecteuler.net")) []
--       , Node (TSNode "Wolfram Mathworld" "" (browse "mathworld.wolfram.com")) []
--       ]
--   ]
--     where
--         browse site = spawn (browser ++ " https://" ++ site)

-- searchTree =
--     [ Node (TSNode "Search Engines" "" (return ()))
--         [ Node (TSNode "WolframAlpha" "" (psearch S.alpha)) []
--         , Node (TSNode "arXiv" "" (psearch S.arXiv)) []
--         , Node (TSNode "AUR" "" (psearch S.aur)) []
--         , Node (TSNode "Dictionary" "" (psearch S.dictionary)) []
--         , Node (TSNode "Github" "" (psearch S.github)) []
--         , Node (TSNode "Google" "" (psearch S.google)) []
--         , Node (TSNode "Hackage" "" (psearch S.hackage)) []
--         , Node (TSNode "Hoogle" "" (psearch S.hoogle)) []
--         , Node (TSNode "IMDB" "" (psearch S.imdb)) []
--         , Node (TSNode "Mathworld" "" (psearch S.mathworld)) []
--         , Node (TSNode "Google Scholar" "" (psearch S.scholar)) []
--         , Node (TSNode "Thesaurus" "" (psearch S.thesaurus)) []
--         , Node (TSNode "Wikipedia" "" (psearch S.wikipedia)) []
--         , Node (TSNode "Youtube" "" (psearch S.youtube)) []
--         ]
--     ]
--         where
--             psearch = S.promptSearch promptConfig
--
-- tsConfig = def { ts_font = xmFont }
